### ISSUE TITLE
Will not build

### ISSUE THREAD

**Issue by gamename** [henriwoodcock/pico-wake-word#10]
Hi.

Great project! But for some reason, it doesn't build anymore.  Attached, is my build log.

[build.log](https://github.com/henriwoodcock/pico-wake-word/files/12456923/build.log)

**Comment by henriwoodcock** [comment]
Hi sorry for not seeing this. You're probably best making sure you update the libraries in `lib` to their latest on main branch. `git submodule update`. You should also go to here https://github.com/raspberrypi/pico-tflmicro and raise an issue if it persists.
