### ISSUE TITLE
Build requires tusb.h but does not exist.

### ISSUE THREAD

**Issue by BoomTei** [henriwoodcock/pico-wake-word#5]
It's an honor to be able to use your project.

I tried to proceed with the build myself, but it stopped due to the problem as shown in the below.

[ 20%] Built target pico-tflmicro
[ 20%] Building CXX object CMakeFiles/pico_micro_speech_analog.dir/src/main.cpp.obj
C:\pico\pico-wake-word\src\main.cpp:19:10: fatal error: tusb.h: No such file or directory
   19 | #include "tusb.h"
      |          ^~~~~~~~
compilation terminated.
NMAKE : fatal error U1077: 'C:\PROGRA~2\GNUARM~1\102020~1\bin\AR10B2~1.EXE' : '0x1' 반환 코드입니다.
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX64\x64\nmake.exe"' : '0x2' 반환 코드입니다.
Stop.
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30037\bin\HostX64\x64\nmake.exe"' : '0x2' 반환 코드입니다.
Stop.

**Comment by henriwoodcock-old** [comment]
Hi @BoomTei,

This repository requires setting up the Pico SDK beforehand. I’ll update the README.md. But to fix your issue:

```bash
# download pico sdk
git clone https://github.com/raspberrypi/pico-sdk.git
cd pico-sdk
git submodule init
git submodule update 
cd ../
export PICO_SDK_PATH=pico-sdk

# build micro speech 
mkdir build
cd build
cmake ..
make
```

Hope this helps, let me know any more issues

**Comment by BoomTei** [comment]
Thanks to your help, the problem has been solved. But another problem has arisen.

[ 83%] Built target hello_pdm_microphone
Scanning dependencies of target usb_microphone
[ 83%] Building C object lib/pico-microphone/examples/usb_microphone/CMakeFiles/usb_microphone.dir/main.c.obj
In file included from C:\pico\pico-sdk\lib\tinyusb\src/tusb.h:80,
                 from C:\pico\pico-wake-word\lib\pico-microphone\examples\usb_microphone\usb_microphone.h:11,
                 from C:\pico\pico-wake-word\lib\pico-microphone\examples\usb_microphone\main.c:17:
C:\pico\pico-sdk\lib\tinyusb\src/class/audio/audio_device.h:40:2: error: #error You must tell the driver the length of the audio function descriptor including IAD descriptor
   40 | #error You must tell the driver the length of the audio function descriptor including IAD descriptor
      |  ^~~~~
In file included from C:\pico\pico-sdk\lib\tinyusb\src/tusb.h:80,
                 from C:\pico\pico-wake-word\lib\pico-microphone\examples\usb_microphone\usb_microphone.h:11,
                 from C:\pico\pico-wake-word\lib\pico-microphone\examples\usb_microphone\main.c:17:
C:\pico\pico-sdk\lib\tinyusb\src/class/audio/audio_device.h:55:2: error: #error You must tell the driver the number of Standard AS Interface Descriptors you have defined in the audio function descriptor!
   55 | #error You must tell the driver the number of Standard AS Interface Descriptors you have defined in the audio function descriptor!
      |  ^~~~~
C:\pico\pico-sdk\lib\tinyusb\src/class/audio/audio_device.h:70:2: error: #error You must define an audio class control request buffer size!
   70 | #error You must define an audio class control request buffer size!
      |  ^~~~~
NMAKE : fatal error U1077: 'C:\PROGRA~2\GNUARM~1\102020~1\bin\AR19DD~1.EXE' : '0x1' 반환 코드입니다.

I don't think the microphone is defined, so I'd appreciate it if you could tell me how to solve the problem.

**Comment by BoomTei** [comment]
> Hi @BoomTei,
> 
> This repository requires setting up the Pico SDK beforehand. I’ll update the README.md. But to fix your issue:
> 
> ```shell
> # download pico sdk
> git clone https://github.com/raspberrypi/pico-sdk.git
> cd pico-sdk
> git submodule init
> git submodule update 
> cd ../
> export PICO_SDK_PATH=pico-sdk
> 
> # build micro speech 
> mkdir build
> cd build
> cmake ..
> make
> ```
> 
> Hope this helps, let me know any more issues

Thanks to your help, the problem has been solved. But another problem has arisen.

[ 83%] Built target hello_pdm_microphone
Scanning dependencies of target usb_microphone
[ 83%] Building C object lib/pico-microphone/examples/usb_microphone/CMakeFiles/usb_microphone.dir/main.c.obj
In file included from C:\pico\pico-sdk\lib\tinyusb\src/tusb.h:80,
from C:\pico\pico-wake-word\lib\pico-microphone\examples\usb_microphone\usb_microphone.h:11,
from C:\pico\pico-wake-word\lib\pico-microphone\examples\usb_microphone\main.c:17:
C:\pico\pico-sdk\lib\tinyusb\src/class/audio/audio_device.h:40:2: error: #error You must tell the driver the length of the audio function descriptor including IAD descriptor
40 | #error You must tell the driver the length of the audio function descriptor including IAD descriptor
| ^~~~~
In file included from C:\pico\pico-sdk\lib\tinyusb\src/tusb.h:80,
from C:\pico\pico-wake-word\lib\pico-microphone\examples\usb_microphone\usb_microphone.h:11,
from C:\pico\pico-wake-word\lib\pico-microphone\examples\usb_microphone\main.c:17:
C:\pico\pico-sdk\lib\tinyusb\src/class/audio/audio_device.h:55:2: error: #error You must tell the driver the number of Standard AS Interface Descriptors you have defined in the audio function descriptor!
55 | #error You must tell the driver the number of Standard AS Interface Descriptors you have defined in the audio function descriptor!
| ^~~~~
C:\pico\pico-sdk\lib\tinyusb\src/class/audio/audio_device.h:70:2: error: #error You must define an audio class control request buffer size!
70 | #error You must define an audio class control request buffer size!
| ^~~~~
NMAKE : fatal error U1077: 'C:\PROGRA2\GNUARM1\1020201\bin\AR19DD1.EXE' : '0x1' 반환 코드입니다.

I don't think the microphone is defined, so I'd appreciate it if you could tell me how to solve the problem.

**Comment by BoomTei** [comment]
> Hi @BoomTei,
> 
> This repository requires setting up the Pico SDK beforehand. I’ll update the README.md. But to fix your issue:
> 
> ```shell
> # download pico sdk
> git clone https://github.com/raspberrypi/pico-sdk.git
> cd pico-sdk
> git submodule init
> git submodule update 
> cd ../
> export PICO_SDK_PATH=pico-sdk
> 
> # build micro speech 
> mkdir build
> cd build
> cmake ..
> make
> ```
> 
> Hope this helps, let me know any more issues

**Comment by henriwoodcock-old** [comment]
Hi @BoomTei, sorry the above command I sent was for an older version. I have just retested the steps from scratch and built the binary. Please use the following steps:

```bash
git clone https://github.com/henriwoodcock/pico-wake-word
git submodule init
cd lib/pico-sdk
git submodule init
cd ../../
mkdir build
cd build
cmake ..
make -j8
```

You will then find all the binary files inside the `build` directory.

I have also updated the `README.md`.

**Comment by BoomTei** [comment]
Hi @henriwoodcock.
I analyzed again and found that the uf2 file was generated normally. The problem is expected to be with pico-microphone\examples\usb_microphone in lib. The CMakeList deletes the part of the add_subdirectory ("examples/usb_microphone") and thus compiles normally.
Also, I checked that it is working normally. Thank you very much.
![success](https://user-images.githubusercontent.com/86457068/123722554-89612700-d8c3-11eb-937b-5554c7b90275.PNG)


If you have time, could you check the appropriate part of the examples/usb_microphone? I think it's a problem caused by the microphone not being defaulted, but I don't know how to solve it.

**Comment by henriwoodcock-old** [comment]
No worries @BoomTei, you can find the pico-microphone repository [here](https://github.com/sandeepmistry/pico-microphone) (where this error is coming from). @sandeepmistry may be able to help you over there.
