### ISSUE TITLE
If this source code can be used to recgonize more than one word defined. Thanks a lot.

### ISSUE THREAD

**Issue by ukicomputers** [henriwoodcock/pico-wake-word#6]

**Comment by henriwoodcock-old** [comment]
yes, you would need to train a new model and update the outputs file : - )

https://github.com/raspberrypi/pico-tflmicro/blob/6ff6387ed1fb3b721b0996583c4af8872980833b/examples/micro_speech/micro_features/micro_model_settings.cpp

**Comment by ukicomputers** [comment]
Thanks a lot ;) @henriwoodcock
