### ISSUE TITLE
how to create own uf2 file??

### ISSUE THREAD

**Issue by salmaShahid** [henriwoodcock/pico-wake-word#7]
I have train my own wake wake detector using tensorflow then convert model to .tflite and convert tflite model to .cc file

Now, I am unable to find how can i create uf2 file from .cc???

can you plz give us solution of how to convert .cc file to uf2.
Thankyou

**Comment by henriwoodcock-old** [comment]
take a look at this issue here: https://github.com/henriwoodcock/pico-wake-word/issues/6.

When initialising this repository you clone the tflmicro repository, you can replace the model file in there and update the micro model settings to reflect your model.

Let me know if you need anymore help
